[[libsixel]]
arch = "aarch64"
git-tree-sha1 = "6f1d10c4ee8b07e0fd021e683ace966dc49049da"
os = "macos"

    [[libsixel.download]]
    sha256 = "48c1d3dd6e7d422fef6a116cfb47b164e04de3a38a6ba47e182c9db852ef789a"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.aarch64-apple-darwin.tar.gz"
[[libsixel]]
arch = "aarch64"
git-tree-sha1 = "360fbf54b1adff2361e026f233e82d15fad58c22"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "37a1af08c26639d992031060a019e8a06c8740f8319e42de76abac65722ea40e"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.aarch64-linux-gnu.tar.gz"
[[libsixel]]
arch = "aarch64"
git-tree-sha1 = "092cb06d479658ad667c12c49e771164095d02f1"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "9ea9c47d97116e4e45399370fb9637d330b523d736a4007ded1cb2ae78d12bed"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.aarch64-linux-musl.tar.gz"
[[libsixel]]
arch = "aarch64"
git-tree-sha1 = "e834b78d55d0c56dc56c7e72b9b659af9eeb5a9f"
os = "freebsd"

    [[libsixel.download]]
    sha256 = "fc00e80532219be579731643650cb22b8b9cd4675334e49e00e4fc012b2f211f"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.aarch64-unknown-freebsd.tar.gz"
[[libsixel]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bf83e8ffa51acd6edcd7ebea5342986e93f3617a"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "afe689e7d5329559f5073f4b6a6c728a67653f22b1c869ad4b234f57674f4240"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.armv6l-linux-gnueabihf.tar.gz"
[[libsixel]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9bf7757941528e9146c57bd78f80e4ac95c733af"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "d3bb073e32049479f61e3c37962be285b55f4d3701514da160428b86cbb19dea"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.armv6l-linux-musleabihf.tar.gz"
[[libsixel]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "960fe4a7cd1fe7f19a97e86915c295b0db949dc7"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "5b3bc0071ae4b2ec6a96e8fd82cda1baac15ff6d8635298eb2ada6a6ddcd3ee1"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.armv7l-linux-gnueabihf.tar.gz"
[[libsixel]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aebbcea18292bb117fb4d37d5ce11685ccf93f01"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "3b2f315d9995bcd5f74514cbaa8a5eb381d5081b1be892897dc3c33db920e4f7"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.armv7l-linux-musleabihf.tar.gz"
[[libsixel]]
arch = "i686"
git-tree-sha1 = "d39bb31d0f028823d9d77f81b99cb5c826046fd1"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "c6cbc97cb03288a8e55e2ab2145d056b56aa348acc5f5f7e47583e76a96436ad"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.i686-linux-gnu.tar.gz"
[[libsixel]]
arch = "i686"
git-tree-sha1 = "655f94c208526faea772c201e5edb8c7e628fdb8"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "252829f7e505540237f52c3d091b8efe60e47dddc4d4e470500a0b4170348008"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.i686-linux-musl.tar.gz"
[[libsixel]]
arch = "i686"
git-tree-sha1 = "c402a243df3e2dccad3b8b5be43cbdf5c9051de8"
os = "windows"

    [[libsixel.download]]
    sha256 = "24b9c44f897da829cd41660dc6e61049a31199832ec9a059752af85ed4fb5295"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.i686-w64-mingw32.tar.gz"
[[libsixel]]
arch = "powerpc64le"
git-tree-sha1 = "edfbb3284d379dae099dfe9d5699b8c6c7a24a43"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "4438b27bca3bdc32d3e20d9bac8ac9501e2be56968f5c649cadf220e57cba08c"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.powerpc64le-linux-gnu.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "167b1b686b32b22cf75a854cc8317507018c8909"
os = "macos"

    [[libsixel.download]]
    sha256 = "354369239b609d245699112ac6126f8e8d8556e1f11294cc204159304cd01a6d"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.x86_64-apple-darwin.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "750ee5c0c80544e64218becc6978f7fa1f38f990"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "1f61d3192a4772fe75a30eefae92dc6dcd7ed01b2aa5406c28214b99134a4080"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.x86_64-linux-gnu.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "d2badcab5f980193ba6b2c9cfef826ad9a72f7b7"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "27ea1ad7075288e47e4dddb9b80be23684d735aeda1a90324e8fff47fddec53a"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.x86_64-linux-musl.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "0f763dc1b3fcc08187165cfbe4523bfbd57db582"
os = "freebsd"

    [[libsixel.download]]
    sha256 = "1d749e75423460e94830bc2c297b3a0d0e45e7b02f9df8c8648d413d2ef92c1b"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.x86_64-unknown-freebsd.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "29ebbdb0f99679bbbf658d1d9e9ec9684ee76e0d"
os = "windows"

    [[libsixel.download]]
    sha256 = "66b841bbdd09f5c9028e4cbb38d5061636a1a3da924d57b75cb7941e68031515"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+1/libsixel.v1.10.3.x86_64-w64-mingw32.tar.gz"
