[[libsixel]]
arch = "aarch64"
git-tree-sha1 = "1feb1bcc1467346ad38068a9f75c5866a74a1c8b"
os = "macos"

    [[libsixel.download]]
    sha256 = "6ac83b7a694313263620ac56680585dbeb4b814518585108870fb8fef8ad5f9f"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.aarch64-apple-darwin.tar.gz"
[[libsixel]]
arch = "aarch64"
git-tree-sha1 = "70d44005fba786a9cb136748c8192e83d93bb984"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "1bdabdf260ee81c865ef61fc2a4e3b2e473aecde95db9a41fd9104000b226e6e"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.aarch64-linux-gnu.tar.gz"
[[libsixel]]
arch = "aarch64"
git-tree-sha1 = "c5df9cc9e9b7035f98badd489e9445d758b1e593"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "871dd83fa147dbd731e6f07bd87161debde6ce24a6ee33470623dbcef369ad94"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.aarch64-linux-musl.tar.gz"
[[libsixel]]
arch = "aarch64"
git-tree-sha1 = "fc1c844bd354fb5165cfac765087a64d0ed3bfc4"
os = "freebsd"

    [[libsixel.download]]
    sha256 = "8e8c83bebff3317b9513a4d59b04b450fb63de4e4fe2ed9d04b365a8ec850f7f"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.aarch64-unknown-freebsd.tar.gz"
[[libsixel]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0b1eaa26a8509293ece3da949ee4cdcb9decf4db"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "0529d0308c34d0e991fffc2297c3be32509228aee404ca5a0e56015542ab0c20"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.armv6l-linux-gnueabihf.tar.gz"
[[libsixel]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "10187f4c70e76c1985e9a2d4830abe11f1b3e596"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "6424f754a115ebc3b17c3fba924b950ecbb5e31bfb49bb1b2a5b871d589a4b1e"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.armv6l-linux-musleabihf.tar.gz"
[[libsixel]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3c7aa4ed31d4dbb8ee4b81ab717b238e960bfd5f"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "0de889809518b47f0ab25ff51d601c82d71be92f7a3c821a88099c8683df70b5"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.armv7l-linux-gnueabihf.tar.gz"
[[libsixel]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "61948d6364a7f9c04944b36371e9357d92de80ae"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "80085d9cdeb482c9e7adddf09d882fa397dc050399ad8f2aabe5eb288c15d0fe"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.armv7l-linux-musleabihf.tar.gz"
[[libsixel]]
arch = "i686"
git-tree-sha1 = "ecec815e7d16aed30fea9818092d6a850e38e0cb"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "026077b24a38a7585ce1abfe7d603aee528b1a9eb2b28fc0bae2a588baf27938"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.i686-linux-gnu.tar.gz"
[[libsixel]]
arch = "i686"
git-tree-sha1 = "003ade12feb01a4b6f03ad94921a63afd0cac5b7"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "5e23abbd4db22e1f447959fbdab05c74faae43575165004b96cbc88a3ac281c5"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.i686-linux-musl.tar.gz"
[[libsixel]]
arch = "i686"
git-tree-sha1 = "752910b6b0aabfa3851bcc670e22eda0199d67b3"
os = "windows"

    [[libsixel.download]]
    sha256 = "4707e9a609c7082ad12ca9e1029f1cc578eb2f078684b1500b43f538ad27952f"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.i686-w64-mingw32.tar.gz"
[[libsixel]]
arch = "powerpc64le"
git-tree-sha1 = "86f7c16b9d5fbad203ccc3e894b06dcca9372828"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "85880846e32b7fc21a38086034b6e393b546617bb046d97a37aa9c65bba1ccea"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.powerpc64le-linux-gnu.tar.gz"
[[libsixel]]
arch = "riscv64"
git-tree-sha1 = "6d1174d4283a4c761e07d3abdd13e232726587f5"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "0e6d98222b45086518b4c5bb053d5a9a8aa924ffd0fff1f9dcb49618518c6012"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.riscv64-linux-gnu.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "f22d794bb483e6a3eb138747fccb2c7b1225709b"
os = "macos"

    [[libsixel.download]]
    sha256 = "19992da0b7c4e0d1ffbe55f24485e50dceeb27aacb6e174f7abdf16ba88483a4"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.x86_64-apple-darwin.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "55dc164530dc9151896ed60a08a8e959c68f15db"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "3c10176708a8e5f1f26a0b793a33675b9160d5f8c007bbe774549294b3587895"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.x86_64-linux-gnu.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "e24865bd09236510e3553e189a6215cef0e60880"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "5d8969b0e3002504496d976c427cca60ac9a629e2aeb65477c315294d1b872c5"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.x86_64-linux-musl.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "5a376aa952a74e71d1efbabd6e5e0f63d7530371"
os = "freebsd"

    [[libsixel.download]]
    sha256 = "5c2a15faca182393d210db905e17e33f0018e5e798dcc76410453a740f3707ae"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.x86_64-unknown-freebsd.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "b9fa96c5d6826190c4c0979a47e7535f2a3209fd"
os = "windows"

    [[libsixel.download]]
    sha256 = "b321a25ce5592547b42f21fa7eb302566c52ee23d9f83a28ef0fcaab768aab78"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.80.702+0/libsixel.v1.80.702.x86_64-w64-mingw32.tar.gz"
