[[libsixel]]
arch = "aarch64"
git-tree-sha1 = "c11c919f0e280a4197b3697a127c2a632abe247a"
os = "macos"

    [[libsixel.download]]
    sha256 = "ef90879b8d8af5772b3989013c261a689940f22c9c5d2e7e66d3ed95cd7facfb"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.aarch64-apple-darwin.tar.gz"
[[libsixel]]
arch = "aarch64"
git-tree-sha1 = "d95014ecc21a48bc13268a1311ebcab3f290c926"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "7e0a9178351054e1d90433a6dff434b7202d7bb0c319240c66e794c74cf2ea8f"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.aarch64-linux-gnu.tar.gz"
[[libsixel]]
arch = "aarch64"
git-tree-sha1 = "e3687d65751613fb209e8658a55aa9f0e9082570"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "f8bb12e773b35a8115611a0a887d8978443f02b950b280296e1a211bacd61949"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.aarch64-linux-musl.tar.gz"
[[libsixel]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d85165a30d39b3696e8d7402653a764b95dbdecf"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "f826068ad7dc508ac6edb409d55347f05a7ba56130826827f59043a33db08ee1"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.armv6l-linux-gnueabihf.tar.gz"
[[libsixel]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7f4775318a1e478962b6330836371336e92a60be"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "b337d2c5badb01cdec0f8f6b7b13d6bd78c26e97f73c7e2404742bf32db0c0f6"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.armv6l-linux-musleabihf.tar.gz"
[[libsixel]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "825ac3087ef43d0340dd37fc33df571dd27afd6b"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "552beb04fb106941369948629da28851204bbe532ee12f193d962da55a186a0f"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.armv7l-linux-gnueabihf.tar.gz"
[[libsixel]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "33e59b930885465d0478ac6aea5e714ae1a07cc0"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "abef9a7a496ae88ca5dadbd27adffcc66f7d90de1e2ef4ac751cd358dd1dd05f"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.armv7l-linux-musleabihf.tar.gz"
[[libsixel]]
arch = "i686"
git-tree-sha1 = "5c75adb5e6ccaa52b3da3b96cc061ce938ec3552"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "48b9609192728cb75512680e2b038f91e0bbd73132ba312faef147624bacd4cd"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.i686-linux-gnu.tar.gz"
[[libsixel]]
arch = "i686"
git-tree-sha1 = "b678f6f8a5c28462cfb3395f6647623760d073f7"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "18420983ef17e32374ae41e1fb7d89356197fee6ddcfc256bacfbc8b668edf78"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.i686-linux-musl.tar.gz"
[[libsixel]]
arch = "i686"
git-tree-sha1 = "5137f1b129365e35a332305f38225020157d2597"
os = "windows"

    [[libsixel.download]]
    sha256 = "64aca76f17887fd78543b94823df6af41501032180c3aad1d5a8ba3d97921556"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.i686-w64-mingw32.tar.gz"
[[libsixel]]
arch = "powerpc64le"
git-tree-sha1 = "c1d73061d0c8306d37cf95bd5c6e17f157714a07"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "e48d34757e5c6be1f26249826c997b2c55cb1b53f58276b41e231dfe839008ab"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.powerpc64le-linux-gnu.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "52110d7101e3b66aadcf208c4af8d63d614ca78d"
os = "macos"

    [[libsixel.download]]
    sha256 = "ba9ff9406f2703aa74baee17629cf611f44a30137e793df7b73748df78af7d4c"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.x86_64-apple-darwin.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "c32c2bdb5bfbe46385385981191b3056081b7b8b"
libc = "glibc"
os = "linux"

    [[libsixel.download]]
    sha256 = "d5be5e0f0005354939704faf094c44a2a2afb1660aa2c4bad5827203943712bb"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.x86_64-linux-gnu.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "3544c0bb3e72c99ebfe976d6ee4072496237241f"
libc = "musl"
os = "linux"

    [[libsixel.download]]
    sha256 = "09065ff9e4de0e5ffe612920292b8bdc4da9ad21b8bce138fc893c4dfaffff56"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.x86_64-linux-musl.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "d21120353f74c0c12933ec950db243e3a36514b2"
os = "freebsd"

    [[libsixel.download]]
    sha256 = "396de5a7f82cacadb33f66378132171dc521c180e44d9cbf7b8cef61e4e5446a"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.x86_64-unknown-freebsd.tar.gz"
[[libsixel]]
arch = "x86_64"
git-tree-sha1 = "687ee57002d9311b7b7649bbaf3461ace33464e9"
os = "windows"

    [[libsixel.download]]
    sha256 = "c372cf717ca4fb84446ba458e18423a0c122ecfcf68a15789a350a4ef7eada8f"
    url = "https://github.com/JuliaBinaryWrappers/libsixel_jll.jl/releases/download/libsixel-v1.10.3+0/libsixel.v1.10.3.x86_64-w64-mingw32.tar.gz"
